{
    "label":"Report",
    "extends":"Core.AlphaCompany.Event",
    "nodes":{
        "Core":{
            "label":"Report",
            "properties":{
                "type":{
                    "type":"String",
                    "enum":"enum:Core.AlphaCompany.ReportTypes"
                }
            }
        },
        "Address":{
            "label":"Address",
            "properties":{
                "country":{
                    "type":"String",
                    "enum":"enum:Core.AlphaCompany.Countries"
                }
            }
        }
    },
    "edges":{
        "Parent":{
            "source":{
                "class":"Core.AlphaCompany.Group"
            },
            "properties":{
                "from":{
                    "type":"Integer",
                    "default":"time:Now"
                },
                "to":{
                    "type":"Integer",
                    "default":"time:Maximum"
                }
            }
        },
        "Reporter":{
            "label":"HAS",
            "accessLevel":"public",
            "source":{
                "class":"Core.Profile"
            },
            "target":"Core"
        },
        "Approver":{
            "label":"APPROVED",
            "accessLevel":"public",
            "source":{
                "class":"Core.Profile"
            },
            "target":"Core"
        },
        "Address":{
            "label":"LOCATED",
            "source":"Core",
            "target":"Address"
        }
    }
}
