{
    "name":"Object",
    "type":"abstract",
    "container":{
        "id":0
    },
    "nodes":{
        "core":{
            "label":"Core",
            "type":"core",
            "properties":{
                "name":{
                    "type":"string"
                },
                "modified":{
                    "type":"integer",
                    "format":"datetime"
                }
            }
        }
    },
    "edges":{
        "container":{
            "label":"HAS",
            "source":{
                "class":"*"
            },
            "target":"core"
        },
        "controllers":{
            "label":"CONTROLS",
            "source":{
                "class":"Core.Profile"
            },
            "target":"core",
            "multiple":true
        }
    }
}