{
    "name":"Class",
    "nodes":{
        "core":{
            "label":"Class"
        }
    },
    "edges":{
        "container":{
            "label":"HAS",
            "source":{
                "class":"*"
            },
            "target":"core",
            "multiple":true
        },
        "instances":{
            "label":"IMPLEMENTS",
            "source":{
                "class":"*"
            },
            "target":"core"
        },
        "superclass":{
            "label":"EXTENDS",
            "source":"core",
            "target":{
                "class":"Class"
            }
        },
        "subclasses":{
            "label":"EXTENDS",
            "source":{
                "class":"Class"
            },
            "multiple":true
        }
    }
}