{
    "class":{
        "id":1
    },
    "nodes":{
        "core":{
            "name":"Team 1"
        },
        "address":{
            "country":"hu"
        },
        "settings":{
            "timeZone":1
        }
    },
    "edges":{
        "container":{
            "source":{
                "id":1
            }
        }
    }
}